steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker build -f Dockerfile -t gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA --build-arg PROJECT_ID=${PROJECT_ID} ."
images:
  - 'gcr.io/${PROJECT_ID}/firebase:latest'
